import { createClient } from "@/supabase/server";
import { Metadata } from "next";
import ClientSideLayout from "./page.client";

export const metadata: Metadata = {
  title: "etudier / Forum",
  description: "Generated by create next app",
};

export default async function Page() {
  const instance = await createClient();
  const posts = await instance
    .from("post")
    .select(
      "content, last_edited, created_at, post_id, user (username), upvote, downvote, report_count, image_public_url"
    )
    .order("created_at", { ascending: false });

  return (
    <main className="flex flex-col min-h-screen">
      <ClientSideLayout serverPosts={posts.data ?? []} />
    </main>
  );
}
