import { createClient } from "@/supabase/server";
import { Metadata } from "next";
import ClientSideLayout from "./page.client";

export const metadata: Metadata = {
  title: "etudier / Notes",
  description: "Generated by create next app",
};

export default async function Page() {
  const instance = await createClient();
  const user = (await instance.auth.getSession()).data.session?.user;
  const notes = await instance.from("note").select("*").eq("user_id", user?.id);

  return (
    <main className="flex flex-col min-h-screen">
      <ClientSideLayout serverNotes={notes.data ?? []} />
    </main>
  );
}
