import { createClient } from "@/supabase/server";
import { Metadata } from "next";
import ClientSideLayout from "./page.client";

export const metadata: Metadata = {
  title: "etudier / Flashcards",
  description: "Generated by create next app",
};

export default async function Page() {
  const instance = await createClient();
  const user = (await instance.auth.getSession()).data.session?.user;
  const flashcard = await instance.from("flashcard").select("*");

  return (
    <main className="flex flex-col min-h-screen">
      <ClientSideLayout user={user} serverFlashcards={flashcard.data ?? []} />
    </main>
  );
}
